### ISSUE TITLE
Does this work on Yosemite?

### ISSUE THREAD

**Issue by dim882** [inket/CustomNC#3]
I get an error 'The action “Run AppleScript” encountered an error.' when I apply changes. Thanks for your help.

**Comment by inket** [comment]
Hey, can you try the new version? 😄

**Comment by dim882** [comment]
Wow, thanks for updating it! I'll give it a shot tonight and let you know.

**Comment by inket** [comment]
Closing this. Please create a new issue if you find any problems!
